networks:
  blognet:
    name: 'blognet'
  traefiknet:
    name: 'traefiknet'
    external: true

services:  
  postgresdb:
    image: postgres:18-bookworm
    container_name: postgresdb
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - blognet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      start_period: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql
      - ./migrations:/app/migrations
    restart: unless-stopped

  blog:
    image: ghcr.io/salor02/cloud-computing-flask:latest
    container_name: blog
    env_file:
      - .env
    ports:
      - "8900:8080"
    networks:
      - blognet
      - traefiknet
    labels:
      traefik.enable: true
      traefik.docker.network: traefiknet 
      traefik.http.routers.cloudflask.entrypoints: websecure
      traefik.http.routers.cloudflask.rule: Host(`cloudflask.salvatoredilorenzo.com`)
      traefik.http.services.cloudflask.loadbalancer.server.port: 8080
      traefik.http.routers.cloudflask.tls: true

    restart: unless-stopped
    depends_on:
      postgresdb:
        condition: service_healthy

volumes:
  pg-data: