"""empty message

Revision ID: 6a159af061ae
Revises: 
Create Date: 2026-04-30 13:46:34.023606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a159af061ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_name', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_views')
    # ### end Alembic commands ###
