name: Build and Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # permissions given to the github token
    permissions:
      contents: read # can read code
      packages: write # can write packages (needed to publish on the registry)

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          # keeps also a specific tag in order to allow a rollback if necessary
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

  # this job runs on a local server
  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Pull new image
        run: docker compose -f /home/salva/cloud-computing-flask/docker-compose.yml pull blog

      - name: Recreate container
        run: docker compose -f /home/salva/cloud-computing-flask/docker-compose.yml up -d --force-recreate blog

      - name: Clean up old images
        run: docker image prune -f

