name: Check Markdown Template

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'posts/en/**/*.md'

jobs:
  validate-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # in order to get the full history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validate Markdown Format
        run: python3 scripts/validate_markdown.py